# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AddField(
            model_name='patientcard',
            name='insurance',
            field=models.TextField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='visit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
