# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_auto_20160603_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='visits.PatientCard'),
        ),
    ]
