# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
