# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 11:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20160603_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ('-date', '-starts')},
        ),
        migrations.AddField(
            model_name='schedule',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 3, 11, 11, 55, 128575, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
